user: <user>
password: <password>
baseURL: <http://www.company-url.com>
defaultProject: <project-name>
issues:
  plan: <project-name>-1
jql:
  active: >-
    sprint in openSprints()
    and sprint not in futureSprints()
    and project=<project-name>
  all: >-
    project=<project-name>
aliases:
  ls: search jql:active
